### ISSUE TITLE
[Userscript] Stash Checker

### ISSUE THREAD

**Issue by timo95** [stashapp/Stash-Docs#6]
**Category:** Utility
**Userscript:** Stash Checker
**Userscript link:** https://gist.github.com/timo95/562b9363d491e3ee281cb46944445fcd
**Description:** Checks if a given scene/performer on one of the supported sites is present in your stash. Shows a checkmark and tooltip for additional information. All supported websites are listed in the metadata `@match` section.
**Author:** timo95
**Author link:** https://github.com/timo95
**Screenshots:**
![SPOILER_grafik](https://user-images.githubusercontent.com/24251362/214900034-4094e3d9-1bcd-4277-a05f-c079711d5453.png)

**Comment by DogmaDragon** [comment]
Added, thanks!
Direct link: https://docs.stashapp.cc/docs/Add-ons/Userscripts/#stash-checker
