### ISSUE TITLE
Querying and Filtering: Specify regex case-sensitive behavior

### ISSUE THREAD

**Issue by echo6ix** [stashapp/Stash-Docs#81]
I think it might be beneficial to note that any regex based filters are in fact **case sensitive**. 

I would suggest the following modifications to https://docs.stashapp.cc/in-app-manual/browsing/#filters

Change the bullet
- from `all matching is case-insensitive`
- to `all matching is case-insensitive (excluding regex filters)`

Within the Filters heading add the following:
```html
<h3>Regex filters</h3>
<ul><li>All regex filters are case-sensitive</li></ul>
```

Both of these should help avoid any ambiguities regarding case sensitivity.

Ideally it would be nice if another bullet was added describing how to create case-insensitive regex filters, which is usually done by appending the case insensitive flag, `/i`, to the regex, but that doesn't work in Stash.

**Comment by DogmaDragon** [comment]
From what I understand, `all matching is case-insensitive` is under keyword section, which only applies to the search field, and they only work with specific fields mentioned in the table above. Would adding the word `keyword` make it more clear?

For regex modifier, it's a good note. 

Can you take a look at https://github.com/stashapp/stash/pull/5200 and see how it looks?
